repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: ['--config', 'pyproject.toml']
      - id: ruff-format
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: ['--config-file', 'pyproject.toml', 'sab']
        pass_filenames: false
